apiVersion: v1
kind: Service
metadata:
  name: pinger-v1-service
  namespace: default
  labels:
    app: pinger
    version: v1
spec:
  selector:
    app: pinger
    version: v1
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
